= Метод {method-name}
:method-name: "Наименование метода"
:revnumber: 1.0
:toc-title: Оглавление
:toc: 
:toclevels: 6
:sectnums:
:sectnumlevels: 6
:sectanchors:
:autonumber:
:icons: font

//Settings
:examples-dir-soap: ../asciidoc/examples/SOAP/
:examples-dir-rest: ../asciidoc/examples/REST/
:schemas: ../asciidoc/schemas/
:method-name-include: method-name
//Settings

toc::[]

[#aim]
== Назначение метода

Этот раздел должен в нескольких предложениях/абзацах содержать основное назначение метода.

[#description]
== Описание работы метода

Головной раздел, вложенные разделы содержат детальную информацию о работе метода.

[#scheme]
=== Схема работы

Схема работы может быть реализована в любой удобной нотации, например в виде Activity или Sequence диаграмм UML.

[plantuml,,svg]
....
include::.puml[]
....

[#-request]
=== Входные параметры

Раздел, в котором приведено полное описание входных параметров метода.

include::{examples-dir-rest}{methon-name-include}-request.adoc[]

[#-response]
=== Выходные параметры

Раздел, в котором приведено полное описание выходных параметров метода.

include::{examples-dir-rest}{method-name-include}-response.adoc[]

[#logic]
=== Логика работы

Основной и объёмный раздел документа, в котором необходимо отразить следующую информацию:

[arabic]
. Все интеграции, которые есть в данном методе. По факту, каждый шаг в логике работы метода должен быть описан. 
. Рекомендуется придерживаться следующей структуры описания:
[arabic]
.. Описание взаимодействия
.. Запрос
.. Ответ
.. Обработка результатов
[arabic]
. Раздел "Описание взаимодействий" должен содержать описание той интеграции, которая осуществлена на этом шаге.
. Раздел "Обработка результатов" должен содержать чёткое описание обработки всех состояний вызова метода/сервиса, с которым осущуствлена интеграция. 

Вышеперечисленный перечень нужно повторить для каждого интеграционного взаимодействия.